export const data = 
[
	{
		issue_title: "Large pothole on Avenue de France",
		category: 1,
		description: "Deep pothole causing traffic hazard",
		address: "Avenue de France, Marrakech",
		neighborhood: "Gueliz",
		date: "2026-01-15",
		status: "pending",
	},
	{
		issue_title: "Broken streetlight near central park",
		category: 2,
		description: "Streetlight not working, creating safety concern",
		address: "Central Park Road, Casablanca",
		neighborhood: "Downtown",
		date: "2026-01-14",
		status: "in progress",
	},
	{
		issue_title: "Damaged sidewalk blocks pedestrians",
		category: 3,
		description: "Uneven sidewalk pavement",
		address: "Hassan II Avenue, Fez",
		neighborhood: "Medina",
		date: "2026-01-30",
		status: "pending",
	},
	{
		issue_title: "Water leak from underground pipe",
		category: 4,
		description: "Water pooling on street surface",
		address: "Mohammed V Boulevard, Rabat",
		neighborhood: "City Center",
		date: "2026-02-02",
		status: "in progress",
	},
	{
		issue_title: "Elevator malfunction in public building",
		category: 5,
		description: "Elevator stuck between floors",
		address: "Government Square, Fez",
		neighborhood: "Administrative District",
		date: "2025-12-12",
		status: "resolved",
	},
	{
		issue_title: "Overflowing trash bins",
		category: 6,
		description: "Multiple bins not collected",
		address: "Market Square, Marrakech",
		neighborhood: "Medina",
		date: "2026-02-20",
		status: "resolved",
	},
];
